# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'SwiftyJSON', '~> 4.0'
pod 'SwiftUIRefresh'
pod 'SDWebImageSwiftUI'
pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
pod 'KakaoSDKAuth'  # 카카오 로그인
pod 'KakaoSDKUser'  # 사용자 관리
pod 'KakaoSDKLink'  # 메시지(카카오링크)

target 'Climbmate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Climbmate

end
